services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: delta:latest
    ports:
      - "8000:80"                     # http://localhost:8000
    env_file:
      - ../.env                        # le .env à la racine du projet
    # ⚠️ En DEV seulement : ça écrase /var/www/html de l'image
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"                   # expose si tu veux te connecter depuis l’hôte
    volumes:
      - pg_data:/bitnami/postgresql   # chemin Bitnami (persistance)
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pg_data:
    driver: local